from typing import Dict, Any, List, Optional, Union
from datetime import datetime
from pydantic import BaseModel, Field

class AgentArtifact(BaseModel):
    """Reference to a file generated by an agent."""
    name: str
    path: str
    type: str  # e.g., "yaml", "parquet", "json", "plot"
    description: Optional[str] = None

class AgentContent(BaseModel):
    """The structured payload of an agent's response."""
    summary: str = Field(..., description="Human-readable summary of the action")
    data: Dict[str, Any] = Field(default_factory=dict, description="Structured domain data")
    artifacts: List[AgentArtifact] = Field(default_factory=list, description="Generated files")

class AgentResult(BaseModel):
    """Standardized output from any agent action."""
    agent: str
    step: str
    status: str = Field(..., description="SUCCESS, FAILURE, or WARNING")
    content: AgentContent
    metadata: Dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.now)

class ConversationContext(BaseModel):
    """The shared state and history of the current workflow iteration."""
    iteration_id: str
    timestamp: datetime = Field(default_factory=datetime.now)
    market_regime: Optional[str] = None
    
    # History of all agent actions
    logs: List[AgentResult] = Field(default_factory=list)
    
    # Shared state/memory
    state: Dict[str, Any] = Field(default_factory=dict)
    
    def add_log(self, result: AgentResult):
        """Add an agent result to the history."""
        self.logs.append(result)
        
    def get_latest_artifact(self, artifact_type: str) -> Optional[AgentArtifact]:
        """Find the most recent artifact of a specific type."""
        for log in reversed(self.logs):
            for artifact in log.content.artifacts:
                if artifact.type == artifact_type:
                    return artifact
        return None
